name: Website Documentation Update
on:
  push:
    branches:
      - main
      - trigger

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'CoLearn-Dev',
              repo: 'CoLearn-Dev.github.io',
              workflow_id: 'repository_dispatch_config.yaml',
              ref: 'main'
            })